# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fray < Formula
  desc "Multi-agent work that flows without losing the thread."
  homepage "https://fray.so"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adamavenir/fray/releases/download/v0.4.0/fray_0.4.0_darwin_amd64.tar.gz"
      sha256 "7e6059521fef4a38472478e73094c682312081ef1bc88cf542057ca1e8e9ae8a"

      def install
        bin.install "fray"
        bin.install "fray-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adamavenir/fray/releases/download/v0.4.0/fray_0.4.0_darwin_arm64.tar.gz"
      sha256 "9246069ca628408b2545d9f5decceb9c5e9d21ac13f514f338713acc9e31982e"

      def install
        bin.install "fray"
        bin.install "fray-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adamavenir/fray/releases/download/v0.4.0/fray_0.4.0_linux_amd64.tar.gz"
      sha256 "228495edd6d2609daab0e55eebca36a7ef3732326e7ae565a27c4601fa23bdab"
      def install
        bin.install "fray"
        bin.install "fray-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adamavenir/fray/releases/download/v0.4.0/fray_0.4.0_linux_arm64.tar.gz"
      sha256 "792ef3fb910c39adad03c461725b0e32128abfe0647676b859a3be0a9230763e"
      def install
        bin.install "fray"
        bin.install "fray-mcp"
      end
    end
  end
end
